### ISSUE TITLE
The distribution of z vector

### ISSUE THREAD

**Issue by ssqiao** [cameronfabbri/Wasserstein-GAN-Tensorflow#1]
Hi! Cameronfabbri. I don't understand why you train the generator with the vector z sampled from the normal distribution while training the critic with the vector z sampled from the uniform distribution. I find the original author trained WGAN in the pytorch code using the same distribution for both generator and critic. Do you have any specific consideration?

**Comment by cameronfabbri** [comment]
That is actually a typo! They should both be a normal distribution. Thank you for letting me know, I'll update and push today.
